version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    networks:
      - app-network
    ports:
      - "9000:9000"   # Port for Laravel's web server (UI + API)
    command: php artisan serve --host=0.0.0.0 --port=9000   # Ensure the app listens on 0.0.0.0

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: admin
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"   # MySQL port

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
