version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-frontend
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    ports:
      - "9000:9000"

  backend:
    image: php:8.1-fpm
    container_name: laravel-backend
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    command: php artisan serve --host=0.0.0.0 --port=8080
    depends_on:
      - frontend
    ports:
      - "8080:8080"

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: admin
    volumes:
      - db-data:/var/lib/mysql
      - ./database/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    ports:
      - "3306:3306"

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
