global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Scraping Prometheus itself

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # Scraping Node Exporter
  
  - job_name: 'glances'
    static_configs:
      - targets: ['glances:61208']  # Scraping Glances
